/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */
/* 
 * NOTE: This file is auto-generated and contains hardcoded values.
 * For local development, use environment variables in .env.local instead.
 * These values are used as fallbacks if environment variables are not set.
 */

// Use environment variables if available, otherwise fall back to hardcoded values
export const projectId = import.meta.env.VITE_SUPABASE_URL 
  ? new URL(import.meta.env.VITE_SUPABASE_URL).hostname.split('.')[0]
  : "ejzipsbdfzixfaiaupds";

export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY 
  || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqemlwc2JkZnppeGZhaWF1cGRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQzMzU0NzcsImV4cCI6MjA3OTkxMTQ3N30.wO2IYiqz2qSOeq-9oVQZ8EMWHWUbDTcxnEB63qDWHtY";